### ISSUE TITLE
Setup complete AWS environment for Push Dashboard

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/push-service#25]
This includes setting up:
- [x] Firehose for notifications landing into S3
- [x] Lambda for processing S3 notification payloads
- [x] EC2 instance for test autopush setup
- [X] EC2 instance for developer dashboard
- [X] Redis instance for lambda to dump recent messages into

Deployment:
- [x] Deploy autopush with firehose running to EC2 test instance
  - [x] mozilla-services/autopush#419
  - [x] mozilla-services/autopush#421
- [x] Deploy and configure S3 triggered push-processor
  - [x] mozilla-services/push-processor#4
  - [x] mozilla-services/push-processor#3
- [x] Deploy push-messages API app
  - [x] mozilla-services/push-messages#1
  - [x] mozilla-services/push-messages#6
  - [x] mozilla-services/push-messages#7
  - [x] mozilla-services/push-messages#8

**Comment by groovecoder** [comment]
On the EC2 instance for developer dashboard, are we considering the existing Deis cluster (of 3 EC2 instances) to serve that purpose? Or do I need to create another deployment of the dashboard on new EC2 instance(s)?

**Comment by bbangert** [comment]
I was going to enable the Push Messages API to be accessible from anywhere so you wouldn't need to be in the same security group.

**Comment by groovecoder** [comment]
Just on the dev environment? I.e., in stage/prod it will be restricted to calls coming from the same security group so the outside world can't hit it?

**Comment by bbangert** [comment]
I'm not sure, we'll need to discuss with ops. I assume for stage it'll be restricted as ops deploys that.

**Comment by bbangert** [comment]
This is now complete.
