### ISSUE TITLE
[meta] Metric: Top Receivers peak requests, per Day, and per Week

### ISSUE THREAD

**Issue by rafrombrc** [mozilla-services/push-service#3]
# Summary

Meta bug covering end-to-end gathering and delivery of the requested "Top Receivers peak requests, per Day and per Week" Push service metric.

Progress on this has been delayed by the need to dial in a Redshift infrastructure for storing "derived streams", i.e. versions of the data stream that have been transformed in some way and are stored outside of the memory space of our stream processing tool. This is needed for this metric because the data set is too large for the state to be maintained entirely within the memory space of a Heka/Hindsight Lua sandbox.

Many more metrics across Push, all of Cloud Services, and all of Mozilla require this, this delay is a one time cost for much long term gain.
# Breakdown and dependencies
- [x] Redshift cluster for development [bug 1218970](https://bugzilla.mozilla.org/show_bug.cgi?id=1218970)
- [x] Lua filter that massages Push endpoint logs into derived stream (#8)
- [x] Production Redshift cluster [bug 1221216](https://bugzilla.mozilla.org/show_bug.cgi?id=1221216)
- [x] Production deploy of derived stream generation job [bug 1224780](https://bugzilla.mozilla.org/show_bug.cgi?id=1224780)
- [x] Email delivery of requested metrics (#14)

**Comment by rafrombrc** [comment]
Progress on this has been delayed by the need to dial in a Redshift infrastructure for storing "derived streams", i.e. versions of the data stream that have been transformed in some way and are stored outside of the memory space of our stream processing tool. This is needed for this metric because the data set is too large for the state to be maintained entirely within the memory space of a Heka/Hindsight Lua sandbox. The steps needed for completion are as follows:

* Initial set up / configuration / access to a Push Redshift cluster for development. Tracked by [bug 1218970](https://bugzilla.mozilla.org/show_bug.cgi?id=1218970).

* Development of a Lua module providing consistent way to specify the schema for, and insert/update/upsert records to, a derived stream.  Tracked by [bug 1219291](https://bugzilla.mozilla.org/show_bug.cgi?id=1219291).

* Development of the filter code that uses the above Lua module to store the push notification request data from which the top receivers request count can be extracted into Redshift. That's the primary task tracked by this issue.

* Once this is all complete and working in a dev environment, a new bugzilla bug will need to be opened to request provisioning of an ops managed Redshift cluster for Push's long term use for this and other metrics.

Note that step 3 depends on step 2, but a significant amount of the work for step 3 can be done in parallel, using ad-hoc code to handle the Redshift table definition and associated data transformation, updating the code to use the provided Lua module when it's available. This is what I'm currently working on.

**Comment by rafrombrc** [comment]
RESOLVED: Requires available Redshift cluster for development [~~bug 1218970~~](https://bugzilla.mozilla.org/show_bug.cgi?id=1218970).

**Comment by rafrombrc** [comment]
Requires Lua filter that massages Push endpoint logs into derived stream (#8).

**Comment by rafrombrc** [comment]
Requires production Redshift cluster.

**Comment by rafrombrc** [comment]
Requires delivery / dashboard specification.

**Comment by ckarlof** [comment]
@rafrombrc As a suggested, I edited the description to:

* have a couple section headings
* included a task list using github markdown tasklists

What do you think?
