### ISSUE TITLE
Announce "Customer Support" label

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/push-service#55]
**Tasks:**
- [x] Create a label for "customer support" actions
- [x] Send email announcing the new label, and preferred format. 
- [x] Create sample issue illustrating template format.

**Estimated task time:**
1 hr

**Comment by jrconlin** [comment]
Sent email:

https://groups.google.com/a/mozilla.com/forum/#!topic/push-service/9J-U2V6McAY
